# -*- coding: utf-8 -*-
"""cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fOFpMsjAQSCn8ZD5m7PMGkdmKyH55tvX
"""

import pandas as pd
import numpy as np

uncleaned=pd.read_excel('/content/Dataset for Data Analytics.xlsx')
uncleaned
uncleaned.info()

uncleaned.isna().sum()

uncleaned['CouponCode']=uncleaned['CouponCode'].fillna('No Coupon')
uncleaned.isna().sum()

uncleaned.duplicated().sum()

uncleaned.duplicated()

uncleaned['PaymentMethod']=uncleaned['PaymentMethod'].astype('category')
uncleaned['Product']=uncleaned['Product'].astype('category')
uncleaned['OrderStatus']=uncleaned['OrderStatus'].astype('category')

uncleaned.info()

float_cols=uncleaned.select_dtypes(include='float64').columns
uncleaned[float_cols]=uncleaned[float_cols].round(2)

uncleaned.describe()

uncleaned['Date'] = pd.to_datetime(uncleaned['Date'])
uncleaned.info()
display(uncleaned.head())

uncleaned.info()
uncleaned

cleaned_data=uncleaned.to_excel('cleaned_data.xlsx',index=False)

from google.colab import drive
drive.mount('/content/drive')